name: Deploy to GitHub Pages and Heroku

on:
  push:
    branches:
      - main
permissions:
  contents: write
  pull-requests: write
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code 🛎
        uses: actions/checkout@v2

      - name: Setup Node 🏗
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install 🔧
        run: |
          cd frontend
          npm install

      - name: Build 🔧
        run: |
          cd frontend
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.7.2
        with:
          branch: gh-pages
          folder: frontend/build

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install MariaDB development libraries
        run: sudo apt-get install libmariadb-dev

      - name: Install backend dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r backend/requirements.txt

      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh

      - name: Deploy backend to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          heroku login
          heroku git:remote -a studentplanner
          git push heroku main
